In [1]:
import numpy as np

# 生成模拟数据
np.random.seed(42)  # 确保结果可复现
m = 100  # 样本数量
X = 2 * np.random.rand(m, 1)  # 输入特征，范围[0, 2)
y = 3 * X + 5 + np.random.randn(m, 1) * 0.5  # 真实关系：y = 3X + 5 + 噪声

In [4]:
X.shape

(100, 1)

**np.random.rand(m,1)**
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
生成X的形状是100*1,值的范围是[0,1)，再乘2就是[0,2)

In [7]:
y.shape

(100, 1)

y是$y=3x+5$形状不变，得到了真实值。

In [14]:
# 参数初始化
W = np.zeros((1, 1))  # 权重矩阵
b = 0.0                # 偏置项
learning_rate = 0.1    # 学习率
epochs = 1000          # 迭代次数

In [15]:
W

array([[0.]])

W是1x1，这证明了实际上就是y=wx+b，X一维，有100个样本

In [16]:
# 训练过程
for epoch in range(epochs):
    # 前向传播：计算预测值
    y_pred = X @ W + b
    
    # 计算均方误差损失（带1/2系数便于求导简化）
    loss = np.mean((y_pred - y) ** 2) / 2
    
    # 计算梯度
    error = y_pred - y
    dW = (X.T @ error) / m  # X转置与误差矩阵相乘，取平均
    db = np.sum(error) / m   # 误差的总和取平均
    
    # 更新权重和偏置
    W -= learning_rate * dW
    b -= learning_rate * db
    
    # 每100次迭代打印损失
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

Epoch 0, Loss: 32.1398
Epoch 100, Loss: 0.1110
Epoch 200, Loss: 0.1012
Epoch 300, Loss: 0.1008
Epoch 400, Loss: 0.1008
Epoch 500, Loss: 0.1008
Epoch 600, Loss: 0.1008
Epoch 700, Loss: 0.1008
Epoch 800, Loss: 0.1008
Epoch 900, Loss: 0.1008


In [17]:
# 输出训练后的参数
print("\n训练后的参数：")
print(f"W = {W[0][0]:.4f}, b = {b:.4f}")


训练后的参数：
W = 2.8851, b = 5.1075


In [34]:
# 推理示例
X_test = np.array([[0.5], [1.5], [2.0]])  # 测试数据 3x1
y_test = X_test @ W + b # W:1x1 相乘结果为3x1 遍历的结果是1x1的数组，因此最后需要使用索引[0]
w = np.array([[3]])
y_true = X_test @ w + 5
print("\n测试结果：")
for x, y, y_t in zip(X_test, y_test, y_true):
    print(f"X = {x[0]:.2f}, 预测y = {y[0]:.2f}, 真实y = {y_t[0]:.2f}")


测试结果：
X = 0.50, 预测y = 6.55, 真实y = 6.50
X = 1.50, 预测y = 9.44, 真实y = 9.50
X = 2.00, 预测y = 10.88, 真实y = 11.00


In [26]:
X_test

array([[0.5],
       [1.5],
       [2. ]])

In [31]:
arr = np.array([
    [1,2],
    [3,4]
])
print(arr.shape) 

(2, 2)


In [32]:
arr[0]

array([1, 2])

In [33]:
arr[0][0]

1

现在明白使用索引的原因了吧？结果为[1]的数组，因此需要使用索引取其中的第一个也是全部的元素